name: Production CI/CD
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup build environment
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      
      - name: Restore NuGet packages
        run: dotnet restore ./CentralService.Authentication/CentralService.Authentication.sln

      - name: Build application
        run: dotnet build ./CentralService.Authentication/CentralService.Authentication.sln -c Release --no-restore
        
      - name: Run unit tests
        run: dotnet test ./CentralService.Authentication/CentralService.Authentication.sln -c Release --no-build
    
      - name: Publish application
        run: dotnet publish ./CentralService.Authentication/CentralService.Authentication.Presentation/CentralService.Authentication.Presentation.csproj -c Release -o ${{ env.DOTNET_ROOT }}/publish

  publish:
    environment: Production
    runs-on: ubuntu-18.04
    needs: build
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: blurrito/centralservice.authentication
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
